-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 11:13:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wild_football
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wild_football
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wild_football` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `wild_football` ;

-- -----------------------------------------------------
-- Table `wild_football`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wild_football`.`teams` ;

CREATE TABLE IF NOT EXISTS `wild_football`.`teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(45) NOT NULL,
  `avAtk` INT NOT NULL,
  `avDef` INT NOT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `wild_football`.`teams` (`team_id`, `teamName`, `avAtk`, `avDef`) VALUES 
('1', 'Wild Bad Asses', '0', '0');
-- -----------------------------------------------------
-- Table `wild_football`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wild_football`.`players` ;

CREATE TABLE IF NOT EXISTS `wild_football`.`players` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `pseudo` VARCHAR(45) NULL DEFAULT NULL,
  `attaque` INT NOT NULL,
  `defense` INT NOT NULL,
  `number` INT NOT NULL,
  `fk_team_id` INT,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `team`
    FOREIGN KEY (`fk_team_id`)
    REFERENCES `wild_football`.`teams` (`team_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `wild_football`.`players` (`player_id`, `name`, `pseudo`, `attaque`, `defense`, `number`) VALUES 
('1', 'Edouard', 'Bob', '90', '90', '10'),
('2', 'Nicolas', 'Nico', '70', '80', '5');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
